version: '3'

services:
  nginx:
    image: nginx
    depends_on:
      - web
    ports:
      - "8080:80"
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
      - ./static:/static:ro
  web:
    build: .
    entrypoint: /run_web.sh
    env_file: web.env
    volumes:
      - ./static:/static
    depends_on:
      - redis
  redis:
    image: "redis"